menu: run in python virtualenv
* manage python requirements using requirements-menu.txt
  installing the exact versions of all dependencies.
* is completely separate from any system-wide installed python packages,
  won't conflict with existing installed python packages.
* minimizes global system requirements down to python and python-virtualenv

virtualenv requires "--seed pip" or it fails with:
    ModuleNotFoundError: No module named 'pip._internal.utils'